// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// -----------------------------------------------------------------------------
using System;  
using NUnit.Framework;

namespace AssemblyCSharp
{

		[TestFixture()]
		public class UnitTest1
		{
				[Test()]
				public void testManager ()
				{
				//actual
				//ManagerScript.changeScene ("Runner");

				//expected
				//Application.loadedLevel ("Runner");
				

				Assertions.Equals (Application.loadedLevel ("Runner"), ManagerScript.changeScene ("Runner"));

				}
		}
}
